service:
  name: best9


custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  crawl:
    handler: handler.crawl
    events:
      - http:
          method: get
          path: crawl

plugins:
  - serverless-plugin-typescript
  - serverless-offline