service:
  name: ts-lambda-puppeteer

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  crawl:
    handler: handler.crawl
    events:
      - http:
          method: get
          path: crawl

plugins:
  - serverless-plugin-typescript
  - serverless-offline
